# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevScriptRunner < Formula
  desc "Sandstorm Dev Script Runner"
  homepage "https://github.com/sandstorm/dev-script-runner"
  version "2.3.1"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sandstorm/dev-script-runner/releases/download/v2.3.1/dev-script-runner_2.3.1_Darwin_arm64.tar.gz"
      sha256 "0377ce1e856b54aca5d1e87b0abc882680adb8a22d24a466b445e9d1c2eb6a49"

      def install
        bin.install "dev-script-runner" => "dev"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sandstorm/dev-script-runner/releases/download/v2.3.1/dev-script-runner_2.3.1_Darwin_x86_64.tar.gz"
      sha256 "3e25956a9313f6987100c022e03dc7967ed9f16844c3a0560002ded474e4759d"

      def install
        bin.install "dev-script-runner" => "dev"
      end
    end
  end
end
