# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevScriptRunner < Formula
  desc "Sandstorm Dev Script Runner"
  homepage "https://github.com/sandstorm/dev-script-runner"
  version "1.1.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sandstorm/Sandstorm.DevScriptRunner/releases/download/v1.1.0/Sandstorm.DevScriptRunner_1.1.0_Darwin_arm64.tar.gz"
      sha256 "436d8f639a2f37844c2c39137a25e1e9301852dbbf94db248b26d762fb6ccc0d"

      def install
        bin.install "dev-script-runner" => "dev"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sandstorm/Sandstorm.DevScriptRunner/releases/download/v1.1.0/Sandstorm.DevScriptRunner_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "a2817069f5f663369635491abc74099fcfe13094674011c4c777914e2b71a7df"

      def install
        bin.install "dev-script-runner" => "dev"
      end
    end
  end
end
