# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dev < Formula
  desc "Sandstorm Dev Script Runner"
  homepage "https://github.com/sandstorm/dev-script-runner"
  version "0.1.2"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sandstorm/Sandstorm.DevScriptRunner/releases/download/v0.1.2/Sandstorm.DevScriptRunner_0.1.2_Darwin_arm64.tar.gz"
      sha256 "9bc012976010bcd9debb9e06ac43093f538448afec6f75e3eed19df2c27bedc6"

      def install
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"dev"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sandstorm/Sandstorm.DevScriptRunner/releases/download/v0.1.2/Sandstorm.DevScriptRunner_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "135df2ab17acca382b7aeecf8c06751236340f89eb7f6138d0fc185ecb5a8b5d"

      def install
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"dev"
      end
    end
  end
end
