# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dev < Formula
  desc "Sandstorm Dev Script Runner"
  homepage "https://github.com/sandstorm/dev-script-runner"
  version "0.1.2"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sandstorm/Sandstorm.DevScriptRunner/releases/download/v0.1.2/Sandstorm.DevScriptRunner_0.1.2_Darwin_arm64.tar.gz"
      sha256 "2c0d9dabdc4ba843fb3b18ea184c9612dc33a19d78d5c6cf9627bb697fdb715b"

      def install
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"dev"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sandstorm/Sandstorm.DevScriptRunner/releases/download/v0.1.2/Sandstorm.DevScriptRunner_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "13414039fd61c06557cd17b78bfdfc80437bfab1471c905fe9f4f9702436f690"

      def install
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"dev"
      end
    end
  end
end
