# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerExecroot < Formula
  desc "Sandstorm Docker Debug Tools"
  homepage "https://github.com/sandstorm/docker-execroot"
  version "2.0.2"
  depends_on :macos

  on_macos do
    url "https://github.com/sandstorm/docker-execroot/releases/download/v2.0.2/docker-execroot_2.0.2_Darwin_x86_64.tar.gz"
    sha256 "92ca81d8985f030a823c929ca807416950c02c53dad855556d3422f8d4b2c256"

    def install
      pkgshare.install Dir["*"]
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the DockerExecroot
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  def caveats
    caveats =
      <<~EOS

        !!! Please run the following commands to finish installing the docker-execroot plugin:

        ---------------------------------------------------------------------------------
        mkdir -p ~/.docker/cli-plugins
        rm -f ~/.docker/cli-plugins/docker-execroot
        ln -s #{pkgshare}/docker-execroot ~/.docker/cli-plugins/docker-execroot

        rm -f ~/.docker/cli-plugins/docker-vscode
        ln -s #{pkgshare}/docker-execroot ~/.docker/cli-plugins/docker-vscode

        rm -f ~/.docker/cli-plugins/docker-phpprofiler
        ln -s #{pkgshare}/docker-execroot ~/.docker/cli-plugins/docker-phpprofiler
        ---------------------------------------------------------------------------------
      EOS

    caveats
  end
end
