# This file was generated by GoReleaser. DO NOT EDIT.
class DockerDebug < Formula
  desc "Sandstorm Docker Debug Tools"
  homepage "https://github.com/sandstorm/docker-execroot"
  version "0.5.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sandstorm/docker-execroot/releases/download/v0.5.0/docker-execroot_0.5.0_Darwin_x86_64.tar.gz"
    sha256 "605ccb64b98317a590bddf66a5b536ded0f139cfa1c858f9109402561fa167fa"
  end

  def install
    mkdir_p File.expand_path('~') + "/.docker/cli-plugins/"
    ln_sf "#{prefix}/docker-execroot", File.expand_path('~') + "/.docker/cli-plugins/docker-execroot"
    ln_sf "#{prefix}/docker-execroot", File.expand_path('~') + "/.docker/cli-plugins/docker-vscode"
  end
end
