# This file was generated by GoReleaser. DO NOT EDIT.
class DockerExecroot < Formula
  desc "Sandstorm Docker Debug Tools"
  homepage "https://github.com/sandstorm/docker-execroot"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sandstorm/docker-execroot/releases/download/1.0.0/docker-execroot_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "50d3b290490cae931dd4eaf732e3c6e7a57c757570cbff6de8057842ea2408a4"
  end

  def caveats
    caveats =
      <<~EOS

        !!! Please run the following commands to finish installing the docker-execroot plugin:

        ---------------------------------------------------------------------------------
        mkdir -p ~/.docker/cli-plugins
        rm -f ~/.docker/cli-plugins/docker-execroot
        ln -s #{pkgshare}/docker-execroot ~/.docker/cli-plugins/docker-execroot

        rm -f ~/.docker/cli-plugins/docker-vscode
        ln -s #{pkgshare}/docker-execroot ~/.docker/cli-plugins/docker-vscode
        ---------------------------------------------------------------------------------
      EOS

    caveats
  end

  def install
    pkgshare.install Dir["*"]
  end
end
