# This file was generated by GoReleaser. DO NOT EDIT.
class DockerExecroot < Formula
  desc "Sandstorm Docker Debug Tools"
  homepage "https://github.com/sandstorm/docker-execroot"
  version "0.6.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sandstorm/docker-execroot/releases/download/v0.6.0/docker-execroot_0.6.0_Darwin_x86_64.tar.gz"
    sha256 "810c330aa9aab97e4eda6e09a91058a72184fc09a92eb07660db033dfdd37237"
  end

  def install
    libexec.install Dir["*"]
    FileUtils.mkdir_p "/Users/sebastian/.docker/cli-plugins/"
    ln_sf "#{libexec}/docker-execroot", File.expand_path('~') + "/.docker/cli-plugins/docker-execroot"
    ln_sf "#{libexec}/docker-execroot", File.expand_path('~') + "/.docker/cli-plugins/docker-vscode"
  end
end
