# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Drydock < Formula
  desc "Drydock - Docker Debug Tools"
  homepage "https://github.com/sandstorm/drydock"
  version "3.0.2"
  depends_on :macos

  on_macos do
    url "https://github.com/sandstorm/drydock/releases/download/v3.0.2/drydock_3.0.2_Darwin_x86_64.tar.gz"
    sha256 "23bce5f2749a372453ccf29137c4596ea7cd977d7b9008195a9948be5c347cf0"

    def install
      libexec.install Dir["*"]
      bin.write_exec_script libexec/"drydock"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Drydock
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end
end
