# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Drydock < Formula
  desc "Drydock - Docker Debug Tools"
  homepage "https://github.com/sandstorm/drydock"
  version "3.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sandstorm/drydock/releases/download/v3.3.0/drydock_Darwin_x86_64.tar.gz"
      sha256 "69f16f93cb227ecee8b3a0f63088c602ef6597a8470caef403eaee04f5a1cab1"

      def install
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"drydock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sandstorm/drydock/releases/download/v3.3.0/drydock_Darwin_arm64.tar.gz"
      sha256 "405759b8cc7b677698766f44d4c227b92e12c5d16185b3f8b657f8619eeeba31"

      def install
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"drydock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sandstorm/drydock/releases/download/v3.3.0/drydock_Linux_x86_64.tar.gz"
      sha256 "2cf77251a3313cd9fc88d03e491f918b8b15d8be3c7fc3f04985af9cde6174ee"

      def install
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"drydock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandstorm/drydock/releases/download/v3.3.0/drydock_Linux_arm64.tar.gz"
      sha256 "3782262990418013d50ce716e18ac70534a5f3eac8b4558e6abad1d23efd48b3"

      def install
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"drydock"
      end
    end
  end
end
