# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SandstormYubikeyAgent < Formula
  desc ""
  homepage "https://github.com/sandstorm/yubikey-agent"
  version "1.0.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/sandstorm/yubikey-agent/releases/download/v1.0.0/yubikey-agent_Darwin_x86_64.tar.gz"
    sha256 "6500dca119b98e5d06302362491d7f3bda6516f07d7ca5a76de6c442a87b7a3d"

    define_method(:install) do
      bin.install "yubikey-agent"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/sandstorm/yubikey-agent/releases/download/v1.0.0/yubikey-agent_Darwin_arm64.tar.gz"
    sha256 "4678ce73c31d67a2813ff9d1c4d4166519b335c51d9cb593f4557a68c132ced5"

    define_method(:install) do
      bin.install "yubikey-agent"
    end
  end

  conflicts_with "yubikey-agent", because: "you'll want to use the sandstorm forked version of yubikey-agent"

  def post_install
    (var/"run").mkpath
    (var/"log").mkpath
  end

  def caveats
    <<~EOS
      To use this SSH agent, add the config to ~/.ssh/config:

        Host *
          IdentityAgent #{var}/run/yubikey-agent.sock
    EOS
  end

  service do
    run [opt_bin/"yubikey-agent", "-l", var/"run/yubikey-agent.sock"]
    keep_alive true
    log_path var/"log/yubikey-agent.log"
    error_log_path var/"log/yubikey-agent.log"
  end

  test do
    socket = testpath/"yubikey-agent.sock"
    fork { exec bin/"yubikey-agent", "-l", socket }
    sleep 1
    assert_predicate socket, :exist?
  end
end
