# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SandstormDependencyAnalysis < Formula
  desc "Sandstorm Dependency Analysis"
  homepage "https://github.com/sandstorm/dependency-analysis"
  version "1.4.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sandstorm/dependency-analysis/releases/download/v1.4.1/dependency-analysis_1.4.1_Darwin_arm64.tar.gz"
      sha256 "626ab183f28e437d4b983c92f035e772c3ca66356aecbdbe812d8830b5ad18db"

      def install
        bin.install "sandstorm-dependency-analysis" => "sda"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sandstorm/dependency-analysis/releases/download/v1.4.1/dependency-analysis_1.4.1_Darwin_x86_64.tar.gz"
      sha256 "a007ce9837a9b14de44f991890bc06e9a0314439336302245c3e81cd92dfa4e3"

      def install
        bin.install "sandstorm-dependency-analysis" => "sda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sandstorm/dependency-analysis/releases/download/v1.4.1/dependency-analysis_1.4.1_Linux_armv6.tar.gz"
      sha256 "e65a327d05e3ff39296948fea54b1c056904a00d94e8d6b9fd3aa39b1a1b31a1"

      def install
        bin.install "sandstorm-dependency-analysis" => "sda"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandstorm/dependency-analysis/releases/download/v1.4.1/dependency-analysis_1.4.1_Linux_arm64.tar.gz"
      sha256 "64433bf47606061fb90de6a2e238bcbd9d13f9ae3de68395564cd0d986edb0da"

      def install
        bin.install "sandstorm-dependency-analysis" => "sda"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sandstorm/dependency-analysis/releases/download/v1.4.1/dependency-analysis_1.4.1_Linux_x86_64.tar.gz"
      sha256 "dcd8df477bf113837a9bbd536254bd23297b30ab3cfcd60d9e338989d32d39c6"

      def install
        bin.install "sandstorm-dependency-analysis" => "sda"
      end
    end
  end
end
