# This file was generated by GoReleaser. DO NOT EDIT.
class Sku < Formula
  desc "Sandstorm Kubernetes Tools"
  homepage "https://github.com/sandstorm/sku"
  version "1.2.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sandstorm/sku/releases/download/1.2.2/sku_1.2.2_Darwin_x86_64.tar.gz"
    sha256 "833bd62e4581b1821426a63c6f1075b1bed474f1df35139e4ff0c4bd9151b86b"
  end

  def install
    libexec.install Dir["*"]
    bin.write_exec_script libexec/"sku"
  end
end
