# This file was generated by GoReleaser. DO NOT EDIT.
class Sku < Formula
  desc "Sandstorm Kubernetes Tools"
  homepage "https://github.com/sandstorm/sku"
  version "1.1.0"

  if OS.mac?
    url "https://github.com/sandstorm/sku/releases/download/1.1.0/sku_1.1.0_Darwin_x86_64.tar.gz"
    sha256 "c4a51f6599d3291093bbcd509dc9be7d4df29e7aa3a723503e826c9035329257"
  elsif OS.linux?
  end

  def install
    bin.install "sku"
    sku_plugins = bin/"sku_plugins"
    sku_plugins.mkpath
    bin.install "sku_plugins/sandstorm.so"
  end
end
