# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Synco < Formula
  desc "Sandstorm Synco"
  homepage "https://github.com/sandstorm/synco"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sandstorm/synco/releases/download/v1.0.0/synco_Darwin_arm64.tar.gz"
      sha256 "2744de843f7e1ec379e1c00e67eb0636bbb0e0eb4b1a049d3f88cb11d61ac391"

      def install
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"synco"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sandstorm/synco/releases/download/v1.0.0/synco_Darwin_x86_64.tar.gz"
      sha256 "ec23e940faa29a1b9c79bb21c8dd7c981c8f0fd2d4c74e6e15109825ce203632"

      def install
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"synco"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sandstorm/synco/releases/download/v1.0.0/synco_Linux_armv6.tar.gz"
      sha256 "90f31c1a91a0b6051521bcc092682d16d8618640d91666609d20a176c2d35495"

      def install
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"synco"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sandstorm/synco/releases/download/v1.0.0/synco_Linux_x86_64.tar.gz"
      sha256 "8faf77a12a0fbef854385a2340b8bc876f0b58a7693bd87e90cc3b6ccb241141"

      def install
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"synco"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandstorm/synco/releases/download/v1.0.0/synco_Linux_arm64.tar.gz"
      sha256 "b304fadd0f95c1d9344ea63559538efd7ca8683f80a25e3df66e0a34a0819f4b"

      def install
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"synco"
      end
    end
  end
end
