# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Synco < Formula
  desc "Sandstorm Synco"
  homepage "https://github.com/sandstorm/synco"
  version "2.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sandstorm/synco/releases/download/v2.1.2/synco_Darwin_x86_64.tar.gz"
      sha256 "dcffb225b64517f0de66899bd458f9c3cadc22959edda36513a8bb836793e069"

      def install
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"synco"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sandstorm/synco/releases/download/v2.1.2/synco_Darwin_arm64.tar.gz"
      sha256 "bd89472d8bc92529547629482f8ef3f84f56845f2a4038df8c220caf87f6fc22"

      def install
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"synco"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandstorm/synco/releases/download/v2.1.2/synco_Linux_x86_64.tar.gz"
      sha256 "a65441c4ccada8beb35931ccdb9aa919f6ebc5b9b48def912bd996fe8fc29727"
      def install
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"synco"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sandstorm/synco/releases/download/v2.1.2/synco_Linux_arm.tar.gz"
      sha256 "b2fb30d6f519f98240e4a8a8c4f2d0a394788ccccc3851bc2d02b2fffb919926"
      def install
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"synco"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandstorm/synco/releases/download/v2.1.2/synco_Linux_arm64.tar.gz"
      sha256 "a4bb623e6a098599e39f8e9dbf01026a5de1cca79b9ef55144cd2e1ecb180d02"
      def install
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"synco"
      end
    end
  end
end
