# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Synco < Formula
  desc "Sandstorm Synco"
  homepage "https://github.com/sandstorm/synco"
  version "2.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sandstorm/synco/releases/download/v2.2.2/synco_Darwin_x86_64.tar.gz"
      sha256 "10bed94c39a6186e50b853034d0bce51c83d6aeaa1d034efdc4deba16de38741"

      define_method(:install) do
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"synco"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sandstorm/synco/releases/download/v2.2.2/synco_Darwin_arm64.tar.gz"
      sha256 "e60dd3cdeffe72593bcc6f206f08df47fe5f2b38ae49dcc33a362c4b860f0abb"

      define_method(:install) do
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"synco"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandstorm/synco/releases/download/v2.2.2/synco_Linux_x86_64.tar.gz"
      sha256 "fdc8296b23f57b1cce8540898bc6597f7ca686b469dc770a59bf0598277ece1e"
      define_method(:install) do
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"synco"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sandstorm/synco/releases/download/v2.2.2/synco_Linux_arm.tar.gz"
      sha256 "1afe02ba9ea86e290a45825d38ef9246e8907d61880e735c141c475bb55c3c7e"
      define_method(:install) do
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"synco"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandstorm/synco/releases/download/v2.2.2/synco_Linux_arm64.tar.gz"
      sha256 "0540915bc71701374ec9043b83e3db21d41e8ece0768266057a6cb86ed09bc10"
      define_method(:install) do
        libexec.install Dir["*"]
        bin.write_exec_script libexec/"synco"
      end
    end
  end
end
